name: save_logs_and_results
runs:
  using: composite
  steps:
  - uses: actions/upload-artifact@v3.1.1
    with:
      name: proxy.output
      path: src/test/regress/proxy.output
  - uses: actions/upload-artifact@v3.1.1
    with:
      name: regress
      path: src/test/regress/results/
  - uses: actions/upload-artifact@v3.1.1
    with:
      name: master.log
      path: src/test/regress/tmp_check/master/log
  - uses: actions/upload-artifact@v3.1.1
    with:
      name: worker.57637.log
      path: src/test/regress/tmp_check/worker.57637/log
  - uses: actions/upload-artifact@v3.1.1
    with:
      name: worker.57638.log
      path: src/test/regress/tmp_check/worker.57638/log
