name: install_extension
inputs:
  pg_major:
    required: false
runs:
  using: composite
  steps:
  - name: Install Extension
    run: sudo tar xfv "${{ github.workspace }}/artifact/install-${{ inputs.pg_major }}.tar" --directory /
    shell: bash
