name: 'Parallelization matrix'
inputs:
  count:
    required: true
    default: 32
outputs:
  json:
    value: ${{ steps.generate_matrix.outputs.json }}
runs:
  using: "composite"
  steps:
    - name: Generate parallelization matrix
      id: generate_matrix
      shell: bash
      run: |-
        json_array="{id: ["
        for ((i = 1; i <= ${{ inputs.count }}; i++)); do
            json_array+=" $i,"
        done
        json_array=${json_array%,}  # Remove the trailing comma
        json_array+=" ]}"
        echo "json=$json_array" >> "$GITHUB_OUTPUT"
