name: citusdata/citus/flaky_test_debugging
on:
  workflow_dispatch:
    inputs:
      flaky_test:
        required: true
        type: string
      flaky_test_runs_per_job:
        required: false
        default: 50
        type: number
env:
  image_suffix: -vbab548a
  pg15_version: 15.3
  PG_MAJOR: 15
  build_image_name: citus/extbuilder
  test_image_name: citus/failtester
jobs:
  set-image-names:
    runs-on: ubuntu-latest
    steps:
      - id: set-build-image-name
        run: echo "image=${{ env.build_image_name }}:${{ env.pg15_version  }}${{ env.image_suffix }}" >> "$GITHUB_OUTPUT"
      - id: set-test-image-name
        run: echo "image=${{ env.test_image_name }}:${{ env.pg15_version  }}${{ env.image_suffix }}" >> "$GITHUB_OUTPUT"
    outputs:
      build_image: ${{ steps.set-build-image-name.outputs.image }}
      test_image: ${{ steps.set-test-image-name.outputs.image }}
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.set-image-names.outputs.build_imageX }}
    steps:
    - run: echo "${{ needs.set-image-names.outputs.build_image }}"
    - uses: actions/checkout@v3.5.0
    - name: Configure, Build, and Install
      run: "./ci/build-citus.sh"
      env:
        PG_MAJOR: "${{ env.pg_major }}"
    - uses: actions/upload-artifact@v3.1.1
      with:
        path: |-
          ./build-${{ env.pg_major }}/*
          ./install-${{ env.pg_major }}.tar
  test-flakyness:
    if: ${{ inputs.flaky_test }}
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.set-image-names.outputs.test_image }}
    needs:
    - build
    env:
      test: "${{ inputs.flaky_test }}"
      runs: "${{ inputs.flaky_test_runs_per_job }}"
      skip: false
    steps:
    - uses: actions/checkout@v3.5.0
    - uses: actions/download-artifact@v3.0.1
      with:
        path: "."
    - name: Detect regression tests need to be ran
      id: detect-regression-tests
      run: |-
        testForDebugging="${{ env.test }}"
        if [ -z "$testForDebugging" ]; then
          detected_changes=$(git diff origin/main... --name-only --diff-filter=AM | (grep 'src/test/regress/sql/.*\.sql\|src/test/regress/spec/.*\.spec\|src/test/regress/citus_tests/test/test_.*\.py' || true))
          tests=${detected_changes}
        else
          tests=$testForDebugging;
        fi
        if [ -z "$tests" ]; then
            echo "No test found."
            gh run cancel ${{ github.run_id }}
            gh run watch ${{ github.run_id }}
        else
          echo "Detected tests " $tests
        fi
        echo "tests=$tests" >> "$GITHUB_OUTPUT"
    - uses: "./.github/actions/install_extension"
      with:
        pg_major: "${{ env.pg_major }}"
    - uses: "./.github/actions/configure"
    - uses: "./.github/actions/enable_core"
    - name: Run minimal tests
      run: |-
        tests_array=(${{ steps.detect-regression-tests.outputs.tests }})
        for test in "${tests_array[@]}"
        do
            test_name=$(echo "$test" | sed -r "s/.+\/(.+)\..+/\1/")
            gosu circleci src/test/regress/citus_tests/run_test.py $test_name --repeat ${{ env.runs }} --use-base-schedule --use-whole-schedule-line
        done
    - uses: "./.github/actions/save_logs_and_results"
    - uses: "./.github/actions/save_regressions"
    - uses: "./.github/actions/stack_trace"
